package org.kuali.student.enrollment.courseoffering.service.cxf;

import org.kuali.student.enrollment.academicrecord.service.SubscriptionActionEnum;
import org.kuali.student.enrollment.courseoffering.service.CourseOfferingCallbackNamespaceConstants;
import org.kuali.student.r2.common.dto.ContextInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.wsaddressing.W3CEndpointReference;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-25T09:43:06.061-04:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = CourseOfferingCallbackNamespaceConstants.NAMESPACE, name = "CoSubscriptionPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CoSubscriptionPortType {

    @WebResult(name = "returnType", targetNamespace = CourseOfferingCallbackNamespaceConstants.NAMESPACE, partName = "the_return")
    @WebMethod(operationName = "SubscribeToActivityOfferings")
    public String subscribeToActivityOfferings(@WebParam(partName = "callback_action", name = "SubscribeToActivityOfferings", targetNamespace = CourseOfferingCallbackNamespaceConstants.NAMESPACE) SubscriptionActionEnum action,
                                               @WebParam(partName = "callback_object", name = "SubscribeToActivityOfferings", targetNamespace = CourseOfferingCallbackNamespaceConstants.NAMESPACE) W3CEndpointReference callbackObject,
                                               @WebParam(partName = "callback_context", name = "SubscribeToActivityOfferings", targetNamespace = CourseOfferingCallbackNamespaceConstants.NAMESPACE)ContextInfo contextInfo
    );
}
